# Generated by Django 6.0.4 on 2026-06-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='has_auth_error',
            field=models.BooleanField(default=False),
        ),
    ]
