# Generated by Django 6.0.4 on 2026-04-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('emails_processed', models.IntegerField(default=0)),
                ('registrations_found', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='accounts.emailaccount')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('site_domain', models.CharField(max_length=255)),
                ('site_favicon', models.URLField(blank=True, default='', max_length=500)),
                ('registered_at', models.DateTimeField(help_text='When the welcome email was received')),
                ('email_subject', models.TextField(blank=True, default='')),
                ('email_from', models.CharField(blank=True, default='', max_length=255)),
                ('gmail_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('confidence', models.FloatField(default=0.5, help_text='Detection confidence 0.0 to 1.0')),
                ('is_verified', models.BooleanField(default=False, help_text='User confirmed this is correct')),
                ('is_dismissed', models.BooleanField(default=False, help_text='User dismissed this detection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='accounts.emailaccount')),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('email_account', 'site_domain')},
            },
        ),
    ]
